name = "orderpack"
version = "0.1.0"
license = "license"
author = "Michel Olagnon"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2022, John S. Urban"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library=true

[[executable]]
name="tablesort"
source-dir="app"
main="tablesort.f90"
[executable.dependencies]
M_CLI2 = { git = "https://github.com/urbanjost/M_CLI2.git" }
M_io   = { git = "https://github.com/urbanjost/M_io.git"   }

[[test]]
name="test_suite_M_orderpack"
source-dir="test"
main="test_suite_orderpack.f90"
[test.dependencies]
M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
