name = "orderpack"
version = "0.1.0"
license = "license"
author = "Michel Olagnon"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2022, John S. Urban"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
