name = "fpm-orderpack"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
description = "fpm plug-in application that displays orderpack documentation"
copyright = "Copyright 2022, John S. Urban"
categories = ["documentation"]
keywords = ["documentation", "orderpack", "fortran", "fpm" ,"General Purpose Fortran" ,"training"]
 
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false

[dependencies]

[dependencies.M_CLI2]
   git = "https://github.com/urbanjost/M_CLI2.git"

[dependencies.M_escape]
   git = "https://github.com/urbanjost/M_escape.git"

[dependencies.M_match]
   git = "https://github.com/urbanjost/M_match.git"

[dependencies.M_strings]
   git = "https://github.com/urbanjost/M_strings.git"

[[executable]]
name = "fpm-orderpack"
source-dir = "app/"
main="fman.f90"
