m_indmed Module Reference
Data Types
interface indmed
Functions/Subroutines
subroutine, private d_indmed (XDONT, INDM)
recursive subroutine, private d_med (XDATT, IDATT, ires_med)
subroutine, private r_indmed (XDONT, INDM)
recursive subroutine, private r_med (XDATT, IDATT, ires_med)
subroutine, private i_indmed (XDONT, INDM)
recursive subroutine, private i_med (XDATT, IDATT, ires_med)
Variables
integer, parameter, private kdp = selected_real_kind(15)
integer, dimension(:), allocatable, save, private idont
Function/Subroutine Documentation
d_indmed()
subroutine, private m_indmed::d_indmed (real (kind=kdp), dimension (:), intent(in) XDONT, integer, intent(out) INDM) [private]
References d_med(), and idont.
d_med()
recursive subroutine, private m_indmed::d_med (real (kind=kdp), dimension (:), intent(in) XDATT, integer, dimension (:), intent(in) IDATT, integer, intent(out) ires_med) [private]
i_indmed()
subroutine, private m_indmed::i_indmed (integer, dimension (:), intent(in) XDONT, integer, intent(out) INDM) [private]
References i_med(), and idont.
i_med()
recursive subroutine, private m_indmed::i_med (integer, dimension (:), intent(in) XDATT, integer, dimension (:), intent(in) IDATT, integer, intent(out) ires_med) [private]
r_indmed()
subroutine, private m_indmed::r_indmed (real, dimension (:), intent(in) XDONT, integer, intent(out) INDM) [private]
References idont, and r_med().
r_med()
recursive subroutine, private m_indmed::r_med (real, dimension (:), intent(in) XDATT, integer, dimension (:), intent(in) IDATT, integer, intent(out) ires_med) [private]
Variable Documentation
idont
integer, dimension(:), allocatable, save, private m_indmed::idont [private]
kdp
integer, parameter, private m_indmed::kdp = selected_real_kind(15) [private]