m_refsor Module Reference
Data Types
interface refsor
Functions/Subroutines
subroutine real64_refsor (INOUTVALS)
recursive subroutine real64_subsor (INOUTVALS, IDEB1, IFIN1)
subroutine, private real64_inssor (INOUTVALS)
subroutine real32_refsor (INOUTVALS)
recursive subroutine real32_subsor (INOUTVALS, IDEB1, IFIN1)
subroutine, private real32_inssor (INOUTVALS)
subroutine int32_refsor (INOUTVALS)
recursive subroutine int32_subsor (INOUTVALS, IDEB1, IFIN1)
subroutine, private int32_inssor (INOUTVALS)
subroutine f_char_refsor (INOUTVALS)
recursive subroutine f_char_subsor (INOUTVALS, IDEB1, IFIN1)
subroutine, private f_char_inssor (INOUTVALS)
Variables
integer, parameter f_char =selected_char_kind(`DEFAULT`)
Function/Subroutine Documentation
f_char_inssor()
subroutine, private m_refsor::f_char_inssor (character(kind=f_char,len=*), dimension (:), intent(inout) INOUTVALS) [private]
! Sorts INOUTVALS into increasing order (Insertion sort)
! __________________________________________________________
      character(kind=f_char,len=*), dimension (:), Intent (InOut) :: INOUTVALS
! __________________________________________________________
      Integer :: ICRS, IDCR
      character(kind=f_char,len=len(INOUTVALS)) :: XWRK
!
      Do icrs = 2, Size (inoutvals)
         xwrk = inoutvals(icrs)
         If (xwrk >= inoutvals(icrs-1)) cycle
         inoutvals(icrs) = inoutvals(icrs-1)
         Do idcr = icrs - 2, 1, - 1
            If (xwrk >= inoutvals(idcr)) Exit
            inoutvals(idcr+1) = inoutvals(idcr)
         End Do
         inoutvals(idcr+1) = xwrk
      End Do
!
f_char_refsor()
subroutine m_refsor::f_char_refsor (character (kind=f_char,len=*), dimension (:), intent(inout) INOUTVALS) [private]
! __________________________________________________________
      character (kind=f_char,len=*), Dimension (:), Intent (InOut) :: INOUTVALS
! __________________________________________________________
      Call f_char_subsor (inoutvals, 1, Size (inoutvals))
      Call f_char_inssor (inoutvals)
References f_char_inssor(), and f_char_subsor().
f_char_subsor()
recursive subroutine m_refsor::f_char_subsor (character(kind=f_char,len=*), dimension (:), intent(inout) INOUTVALS, integer, intent(in) IDEB1, integer, intent(in) IFIN1) [private]
! Sorts INOUTVALS from IDEB1 to IFIN1
! __________________________________________________________
      character(kind=f_char,len=*), dimension (:), Intent (InOut) :: INOUTVALS
      Integer, Intent (In) :: IDEB1, IFIN1
! __________________________________________________________
      character(kind=f_char,len=len(INOUTVALS)) :: XPIV, XWRK
      Integer, Parameter :: NINS = 16 ! Max for insertion sort
      Integer :: ICRS, IDEB, IDCR, IFIN, IMIL
!
      ideb = ideb1
      ifin = ifin1
!
! If we don't have enough values to make it worth while, we leave
! them unsorted, and the final insertion sort will take care of them
!
      If ((ifin - ideb) > nins) Then
         imil = (ideb+ifin) / 2
!
! One chooses a pivot, median of 1st, last, and middle values
!
         If (inoutvals(imil) < inoutvals(ideb)) Then
            xwrk = inoutvals(ideb)
            inoutvals(ideb) = inoutvals(imil)
            inoutvals(imil) = xwrk
         End If
         If (inoutvals(imil) > inoutvals(ifin)) Then
            xwrk = inoutvals(ifin)
            inoutvals(ifin) = inoutvals(imil)
            inoutvals(imil) = xwrk
            If (inoutvals(imil) < inoutvals(ideb)) Then
               xwrk = inoutvals(ideb)
               inoutvals(ideb) = inoutvals(imil)
               inoutvals(imil) = xwrk
            End If
         End If
         xpiv = inoutvals(imil)
!
! One exchanges values to put those > pivot in the end and
! those <= pivot at the beginning
!
         icrs = ideb
         idcr = ifin
         ech2: Do
            Do
               icrs = icrs + 1
               If (icrs >= idcr) Then
!
! the first > pivot is IDCR
! the last <= pivot is ICRS-1
! Note: If one arrives here on the first iteration, then
! the pivot is the maximum of the set, the last value is equal
! to it, and one can reduce by one the size of the set to process,
! as if INOUTVALS (IFIN) > XPIV
!
                  Exit ech2
!
               End If
               If (inoutvals(icrs) > xpiv) Exit
            End Do
            Do
               If (inoutvals(idcr) <= xpiv) Exit
               idcr = idcr - 1
               If (icrs >= idcr) Then
!
! The last value < pivot is always ICRS-1
!
                  Exit ech2
               End If
            End Do
!
            xwrk = inoutvals(idcr)
            inoutvals(idcr) = inoutvals(icrs)
            inoutvals(icrs) = xwrk
         End Do ech2
!
! One now sorts each of the two sub-intervals
!
         Call f_char_subsor (inoutvals, ideb1, icrs-1)
         Call f_char_subsor (inoutvals, idcr, ifin1)
      End If
int32_inssor()
subroutine, private m_refsor::int32_inssor (integer(kind=int32), dimension (:), intent(inout) INOUTVALS) [private]
! Sorts INOUTVALS into increasing order (Insertion sort)
! __________________________________________________________
      Integer(kind=int32), dimension (:), Intent (InOut) :: INOUTVALS
! __________________________________________________________
      Integer :: ICRS, IDCR
      Integer(kind=int32) :: XWRK
!
      Do icrs = 2, Size (inoutvals)
         xwrk = inoutvals(icrs)
         If (xwrk >= inoutvals(icrs-1)) cycle
         inoutvals(icrs) = inoutvals(icrs-1)
         Do idcr = icrs - 2, 1, - 1
            If (xwrk >= inoutvals(idcr)) Exit
            inoutvals(idcr+1) = inoutvals(idcr)
         End Do
         inoutvals(idcr+1) = xwrk
      End Do
!
int32_refsor()
subroutine m_refsor::int32_refsor (integer (kind=int32), dimension (:), intent(inout) INOUTVALS) [private]
! __________________________________________________________
      Integer (kind=int32), Dimension (:), Intent (InOut) :: INOUTVALS
! __________________________________________________________
      Call int32_subsor (inoutvals, 1, Size (inoutvals))
      Call int32_inssor (inoutvals)
References int32_inssor(), and int32_subsor().
int32_subsor()
recursive subroutine m_refsor::int32_subsor (integer(kind=int32), dimension (:), intent(inout) INOUTVALS, integer, intent(in) IDEB1, integer, intent(in) IFIN1) [private]
! Sorts INOUTVALS from IDEB1 to IFIN1
! __________________________________________________________
      Integer(kind=int32), dimension (:), Intent (InOut) :: INOUTVALS
      Integer, Intent (In) :: IDEB1, IFIN1
! __________________________________________________________
      Integer(kind=int32) :: XPIV, XWRK
      Integer, Parameter :: NINS = 16 ! Max for insertion sort
      Integer :: ICRS, IDEB, IDCR, IFIN, IMIL
!
      ideb = ideb1
      ifin = ifin1
!
! If we don't have enough values to make it worth while, we leave
! them unsorted, and the final insertion sort will take care of them
!
      If ((ifin - ideb) > nins) Then
         imil = (ideb+ifin) / 2
!
! One chooses a pivot, median of 1st, last, and middle values
!
         If (inoutvals(imil) < inoutvals(ideb)) Then
            xwrk = inoutvals(ideb)
            inoutvals(ideb) = inoutvals(imil)
            inoutvals(imil) = xwrk
         End If
         If (inoutvals(imil) > inoutvals(ifin)) Then
            xwrk = inoutvals(ifin)
            inoutvals(ifin) = inoutvals(imil)
            inoutvals(imil) = xwrk
            If (inoutvals(imil) < inoutvals(ideb)) Then
               xwrk = inoutvals(ideb)
               inoutvals(ideb) = inoutvals(imil)
               inoutvals(imil) = xwrk
            End If
         End If
         xpiv = inoutvals(imil)
!
! One exchanges values to put those > pivot in the end and
! those <= pivot at the beginning
!
         icrs = ideb
         idcr = ifin
         ech2: Do
            Do
               icrs = icrs + 1
               If (icrs >= idcr) Then
!
! the first > pivot is IDCR
! the last <= pivot is ICRS-1
! Note: If one arrives here on the first iteration, then
! the pivot is the maximum of the set, the last value is equal
! to it, and one can reduce by one the size of the set to process,
! as if INOUTVALS (IFIN) > XPIV
!
                  Exit ech2
!
               End If
               If (inoutvals(icrs) > xpiv) Exit
            End Do
            Do
               If (inoutvals(idcr) <= xpiv) Exit
               idcr = idcr - 1
               If (icrs >= idcr) Then
!
! The last value < pivot is always ICRS-1
!
                  Exit ech2
               End If
            End Do
!
            xwrk = inoutvals(idcr)
            inoutvals(idcr) = inoutvals(icrs)
            inoutvals(icrs) = xwrk
         End Do ech2
!
! One now sorts each of the two sub-intervals
!
         Call int32_subsor (inoutvals, ideb1, icrs-1)
         Call int32_subsor (inoutvals, idcr, ifin1)
      End If
real32_inssor()
subroutine, private m_refsor::real32_inssor (real(kind=real32), dimension (:), intent(inout) INOUTVALS) [private]
! Sorts INOUTVALS into increasing order (Insertion sort)
! __________________________________________________________
      Real(kind=real32), dimension (:), Intent (InOut) :: inoutvals
! __________________________________________________________
      Integer :: ICRS, IDCR
      Real(kind=real32) :: xwrk
!
      Do icrs = 2, Size (inoutvals)
         xwrk = inoutvals(icrs)
         If (xwrk >= inoutvals(icrs-1)) cycle
         inoutvals(icrs) = inoutvals(icrs-1)
         Do idcr = icrs - 2, 1, - 1
            If (xwrk >= inoutvals(idcr)) Exit
            inoutvals(idcr+1) = inoutvals(idcr)
         End Do
         inoutvals(idcr+1) = xwrk
      End Do
!
real32_refsor()
subroutine m_refsor::real32_refsor (real (kind=real32), dimension (:), intent(inout) INOUTVALS) [private]
! __________________________________________________________
      Real (kind=real32), Dimension (:), Intent (InOut) :: inoutvals
! __________________________________________________________
      Call real32_subsor (inoutvals, 1, Size (inoutvals))
      Call real32_inssor (inoutvals)
References real32_inssor(), and real32_subsor().
real32_subsor()
recursive subroutine m_refsor::real32_subsor (real(kind=real32), dimension (:), intent(inout) INOUTVALS, integer, intent(in) IDEB1, integer, intent(in) IFIN1) [private]
! Sorts INOUTVALS from IDEB1 to IFIN1
! __________________________________________________________
      Real(kind=real32), dimension (:), Intent (InOut) :: inoutvals
      Integer, Intent (In) :: IDEB1, IFIN1
! __________________________________________________________
      Real(kind=real32) :: xpiv, xwrk
      Integer, Parameter :: NINS = 16 ! Max for insertion sort
      Integer :: ICRS, IDEB, IDCR, IFIN, IMIL
!
      ideb = ideb1
      ifin = ifin1
!
! If we don't have enough values to make it worth while, we leave
! them unsorted, and the final insertion sort will take care of them
!
      If ((ifin - ideb) > nins) Then
         imil = (ideb+ifin) / 2
!
! One chooses a pivot, median of 1st, last, and middle values
!
         If (inoutvals(imil) < inoutvals(ideb)) Then
            xwrk = inoutvals(ideb)
            inoutvals(ideb) = inoutvals(imil)
            inoutvals(imil) = xwrk
         End If
         If (inoutvals(imil) > inoutvals(ifin)) Then
            xwrk = inoutvals(ifin)
            inoutvals(ifin) = inoutvals(imil)
            inoutvals(imil) = xwrk
            If (inoutvals(imil) < inoutvals(ideb)) Then
               xwrk = inoutvals(ideb)
               inoutvals(ideb) = inoutvals(imil)
               inoutvals(imil) = xwrk
            End If
         End If
         xpiv = inoutvals(imil)
!
! One exchanges values to put those > pivot in the end and
! those <= pivot at the beginning
!
         icrs = ideb
         idcr = ifin
         ech2: Do
            Do
               icrs = icrs + 1
               If (icrs >= idcr) Then
!
! the first > pivot is IDCR
! the last <= pivot is ICRS-1
! Note: If one arrives here on the first iteration, then
! the pivot is the maximum of the set, the last value is equal
! to it, and one can reduce by one the size of the set to process,
! as if INOUTVALS (IFIN) > XPIV
!
                  Exit ech2
!
               End If
               If (inoutvals(icrs) > xpiv) Exit
            End Do
            Do
               If (inoutvals(idcr) <= xpiv) Exit
               idcr = idcr - 1
               If (icrs >= idcr) Then
!
! The last value < pivot is always ICRS-1
!
                  Exit ech2
               End If
            End Do
!
            xwrk = inoutvals(idcr)
            inoutvals(idcr) = inoutvals(icrs)
            inoutvals(icrs) = xwrk
         End Do ech2
!
! One now sorts each of the two sub-intervals
!
         Call real32_subsor (inoutvals, ideb1, icrs-1)
         Call real32_subsor (inoutvals, idcr, ifin1)
      End If
real64_inssor()
subroutine, private m_refsor::real64_inssor (real(kind=real64), dimension (:), intent(inout) INOUTVALS) [private]
! Sorts INOUTVALS into increasing order (Insertion sort)
! __________________________________________________________
      Real(kind=real64), dimension (:), Intent (InOut) :: inoutvals
! __________________________________________________________
      Integer :: ICRS, IDCR
      Real(kind=real64) :: xwrk
!
      Do icrs = 2, Size (inoutvals)
         xwrk = inoutvals(icrs)
         If (xwrk >= inoutvals(icrs-1)) cycle
         inoutvals(icrs) = inoutvals(icrs-1)
         Do idcr = icrs - 2, 1, - 1
            If (xwrk >= inoutvals(idcr)) Exit
            inoutvals(idcr+1) = inoutvals(idcr)
         End Do
         inoutvals(idcr+1) = xwrk
      End Do
!
real64_refsor()
subroutine m_refsor::real64_refsor (real (kind=real64), dimension (:), intent(inout) INOUTVALS) [private]
NAME
sort(3f) - [orderpack:SORT] Sorts array into ascending order (Quicksort)
SYNOPSIS
 Subroutine Sort (INOUTVALS)

   ${TYPE} (kind=${KIND}), Intent (InOut) :: INOUTVALS(:)

Where ${TYPE}(kind=${KIND}) may be

   o Real(kind=real32)
   o Real(kind=real64)
   o Integer(kind=int32)
   o Character(kind=selected_char_kind("DEFAULT"),len=*)
DESCRIPTION
Sorts INOUTVALS into ascending order (Quicksort)
This version is not optimized for performance, and is thus not as difficult to read as some other ones.
Internally, This subroutine uses Quick-sort in a recursive implementation, and insertion sort for the last steps with small subsets. It does not use any work array.
The Quick-sort chooses a `pivot` in the set, and explores the array from both ends, looking for a value > pivot with the increasing index, for a value <= pivot with the decreasing index, and swapping them when it has found one of each. The array is then subdivided in two subsets:
{ values <= pivot} {pivot} {values > pivot}
It then recursively the procedure to sort each subset. When the size of the subarray is small enough, it switches to an insertion sort that is faster for very small sets.
OPTIONS
INOUTVALS array to sort
EXAMPLES
Sample program:
program demo_sort ! sort array in ascending order use,intrinsic :: iso_fortran_env, only : int32, real32, real64 use M_orderpack, only : sort implicit none ! an insertion sort is very efficient for very small arrays ! but generally slower than methods like quicksort and mergesort. real(kind=real64) :: valsd(2000) integer :: i call random_seed() call random_number(valsd) valsd=valsd*1000000.0-500000.0 call sort(valsd) do i=1,size(valsd)-1 if (valsd(i+1).lt.valsd(i))then write(*,*)'not sorted' stop 3 endif enddo write(*,*)'random arrays are now sorted' end program demo_sort
Results:
random arrays are now sorted
AUTHOR
Michel Olagnon - Apr. 2000
MAINTAINER
John Urban, 2022.04.16
LICENSE
CC0-1.0
! __________________________________________________________
      Real (kind=real64), Dimension (:), Intent (InOut) :: inoutvals
! __________________________________________________________
      Call real64_subsor (inoutvals, 1, Size (inoutvals))
      Call real64_inssor (inoutvals)
References real64_inssor(), and real64_subsor().
real64_subsor()
recursive subroutine m_refsor::real64_subsor (real(kind=real64), dimension (:), intent(inout) INOUTVALS, integer, intent(in) IDEB1, integer, intent(in) IFIN1) [private]
! Sorts INOUTVALS from IDEB1 to IFIN1
! __________________________________________________________
      Real(kind=real64), dimension (:), Intent (InOut) :: inoutvals
      Integer, Intent (In) :: IDEB1, IFIN1
! __________________________________________________________
      Real(kind=real64) :: xpiv, xwrk
      Integer, Parameter :: NINS = 16 ! Max for insertion sort
      Integer :: ICRS, IDEB, IDCR, IFIN, IMIL
!
      ideb = ideb1
      ifin = ifin1
!
! If we don't have enough values to make it worth while, we leave
! them unsorted, and the final insertion sort will take care of them
!
      If ((ifin - ideb) > nins) Then
         imil = (ideb+ifin) / 2
!
! One chooses a pivot, median of 1st, last, and middle values
!
         If (inoutvals(imil) < inoutvals(ideb)) Then
            xwrk = inoutvals(ideb)
            inoutvals(ideb) = inoutvals(imil)
            inoutvals(imil) = xwrk
         End If
         If (inoutvals(imil) > inoutvals(ifin)) Then
            xwrk = inoutvals(ifin)
            inoutvals(ifin) = inoutvals(imil)
            inoutvals(imil) = xwrk
            If (inoutvals(imil) < inoutvals(ideb)) Then
               xwrk = inoutvals(ideb)
               inoutvals(ideb) = inoutvals(imil)
               inoutvals(imil) = xwrk
            End If
         End If
         xpiv = inoutvals(imil)
!
! One exchanges values to put those > pivot in the end and
! those <= pivot at the beginning
!
         icrs = ideb
         idcr = ifin
         ech2: Do
            Do
               icrs = icrs + 1
               If (icrs >= idcr) Then
!
! the first > pivot is IDCR
! the last <= pivot is ICRS-1
! Note: If one arrives here on the first iteration, then
! the pivot is the maximum of the set, the last value is equal
! to it, and one can reduce by one the size of the set to process,
! as if INOUTVALS (IFIN) > XPIV
!
                  Exit ech2
!
               End If
               If (inoutvals(icrs) > xpiv) Exit
            End Do
            Do
               If (inoutvals(idcr) <= xpiv) Exit
               idcr = idcr - 1
               If (icrs >= idcr) Then
!
! The last value < pivot is always ICRS-1
!
                  Exit ech2
               End If
            End Do
!
            xwrk = inoutvals(idcr)
            inoutvals(idcr) = inoutvals(icrs)
            inoutvals(icrs) = xwrk
         End Do ech2
!
! One now sorts each of the two sub-intervals
!
         Call real64_subsor (inoutvals, ideb1, icrs-1)
         Call real64_subsor (inoutvals, idcr, ifin1)
      End If
Variable Documentation
f_char
integer, parameter m_refsor::f_char =selected_char_kind(`DEFAULT`) [private]
integer,parameter :: f_char=selected_char_kind("DEFAULT")